engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "**.go"

exclude_paths:
  - "**_test.go"
  - "**/vendor/**/*"
